import type { MonsterData } from '@/lib/types/battle-extended'
import { SKILL_TEMPLATES } from './monster-database'

// 확장된 몬스터 데이터베이스 (추가 86종)
export const EXTENDED_MONSTER_DATABASE: { [id: string]: MonsterData } = {
  // === 초급 몬스터 추가 (레벨 1-10) ===
  rabbit_white: {
    id: 'rabbit_white',
    name: '하얀 토끼',
    description: '평화로운 초원에 서식하는 토끼',
    emoji: '🐰',
    tier: 'common',
    stats: {
      level: 1,
      hp: 40,
      maxHp: 40,
      mp: 10,
      maxMp: 10,
      attack: 6,
      magicAttack: 4,
      defense: 2,
      magicDefense: 2,
      speed: 15,
      accuracy: 95,
      evasion: 0.15,
      critical: 0.05,
      criticalDamage: 1.5,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'quick_hop',
        name: '재빠른 도약',
        description: '빠르게 뛰어오르며 공격',
        type: 'damage',
        damageType: 'physical',
        element: 'neutral',
        power: 90,
        accuracy: 100,
        mpCost: 0,
        cooldown: 0,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash'
      }
    ]
  },

  bee_worker: {
    id: 'bee_worker',
    name: '일벌',
    description: '부지런히 일하는 벌',
    emoji: '🐝',
    tier: 'common',
    stats: {
      level: 2,
      hp: 45,
      maxHp: 45,
      mp: 15,
      maxMp: 15,
      attack: 8,
      magicAttack: 6,
      defense: 3,
      magicDefense: 3,
      speed: 18,
      accuracy: 95,
      evasion: 0.1,
      critical: 0.1,
      criticalDamage: 1.5,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'sting',
        name: '침 공격',
        description: '독침으로 찌른다',
        type: 'damage',
        damageType: 'physical',
        element: 'poison',
        power: 100,
        accuracy: 95,
        mpCost: 5,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash',
        statusEffect: {
          id: 'bee_poison',
          name: '벌독',
          type: 'debuff',
          damagePerTurn: 5,
          duration: 3,
          stackable: true,
          value: 5,
          chance: 50
        }
      }
    ],
    weaknesses: ['fire', 'ice']
  },

  spider_small: {
    id: 'spider_small',
    name: '작은 거미',
    description: '어둠 속에 숨어있는 거미',
    emoji: '🕷️',
    tier: 'common',
    stats: {
      level: 3,
      hp: 55,
      maxHp: 55,
      mp: 20,
      maxMp: 20,
      attack: 10,
      magicAttack: 8,
      defense: 4,
      magicDefense: 4,
      speed: 12,
      accuracy: 95,
      evasion: 0.08,
      critical: 0.12,
      criticalDamage: 1.6,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'web_shot',
        name: '거미줄 발사',
        description: '끈적한 거미줄을 발사',
        type: 'damage',
        damageType: 'physical',
        element: 'neutral',
        power: 80,
        accuracy: 90,
        mpCost: 10,
        cooldown: 3,
        currentCooldown: 0,
        targetType: 'single',
        range: 2,
        animation: 'projectile',
        statusEffect: {
          id: 'web_slow',
          name: '거미줄',
          type: 'debuff',
          stats: { speed: -10 },
          duration: 2,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ],
    resistances: ['poison']
  },

  fairy_light: {
    id: 'fairy_light',
    name: '빛의 요정',
    description: '빛나는 작은 요정',
    emoji: '🧚',
    tier: 'common',
    stats: {
      level: 4,
      hp: 60,
      maxHp: 60,
      mp: 40,
      maxMp: 40,
      attack: 8,
      magicAttack: 15,
      defense: 5,
      magicDefense: 8,
      speed: 14,
      accuracy: 95,
      evasion: 0.12,
      critical: 0.08,
      criticalDamage: 1.5,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'light_beam',
        name: '빛의 광선',
        description: '성스러운 빛을 발사',
        type: 'damage',
        damageType: 'magical',
        element: 'light',
        power: 120,
        accuracy: 95,
        mpCost: 15,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 3,
        animation: 'projectile'
      },
      {
        id: 'fairy_heal',
        name: '요정의 치유',
        description: '스스로를 치유',
        type: 'heal',
        healAmount: 30,
        mpCost: 20,
        cooldown: 5,
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0
      }
    ],
    weaknesses: ['dark'],
    resistances: ['light']
  },

  snake_green: {
    id: 'snake_green',
    name: '초록 뱀',
    description: '풀숲에 숨어있는 뱀',
    emoji: '🐍',
    tier: 'common',
    stats: {
      level: 5,
      hp: 70,
      maxHp: 70,
      mp: 25,
      maxMp: 25,
      attack: 12,
      magicAttack: 10,
      defense: 6,
      magicDefense: 5,
      speed: 11,
      accuracy: 95,
      evasion: 0.07,
      critical: 0.15,
      criticalDamage: 1.8,
      critRate: 0.1,
      dodgeRate: 0.2
    },
    skills: [
      {
        id: 'venomous_bite',
        name: '독이빨',
        description: '독이 있는 이빨로 문다',
        type: 'damage',
        damageType: 'physical',
        element: 'poison',
        power: 130,
        accuracy: 90,
        mpCost: 10,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash',
        statusEffect: {
          id: 'snake_venom',
          name: '뱀독',
          type: 'debuff',
          damagePerTurn: 8,
          duration: 4,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ],
    weaknesses: ['ice'],
    resistances: ['poison']
  },

  plant_carnivorous: {
    id: 'plant_carnivorous',
    name: '식인 식물',
    description: '움직이는 위험한 식물',
    emoji: '🌱',
    tier: 'common',
    stats: {
      level: 6,
      hp: 85,
      maxHp: 85,
      mp: 30,
      maxMp: 30,
      attack: 14,
      magicAttack: 12,
      defense: 8,
      magicDefense: 6,
      speed: 5,
      accuracy: 95,
      evasion: 0.02,
      critical: 0.1,
      criticalDamage: 1.5,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'vine_whip',
        name: '덩굴 채찍',
        description: '덩굴로 후려친다',
        type: 'damage',
        damageType: 'physical',
        element: 'earth',
        power: 140,
        accuracy: 95,
        mpCost: 12,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 2,
        animation: 'projectile'
      },
      {
        id: 'absorb',
        name: '흡수',
        description: '적의 생명력을 흡수',
        type: 'damage',
        damageType: 'magical',
        element: 'earth',
        power: 80,
        accuracy: 100,
        mpCost: 20,
        cooldown: 4,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash',
        healAmount: 40
      }
    ],
    weaknesses: ['fire', 'ice'],
    resistances: ['water', 'earth']
  },

  ghost_wisp: {
    id: 'ghost_wisp',
    name: '윌오위스프',
    description: '떠도는 영혼의 불꽃',
    emoji: '👻',
    tier: 'common',
    stats: {
      level: 7,
      hp: 75,
      maxHp: 75,
      mp: 50,
      maxMp: 50,
      attack: 10,
      magicAttack: 18,
      defense: 4,
      magicDefense: 10,
      speed: 13,
      accuracy: 95,
      evasion: 0.2,
      critical: 0.08,
      criticalDamage: 1.5,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'soul_burn',
        name: '영혼 태우기',
        description: '영혼을 태우는 불꽃',
        type: 'damage',
        damageType: 'magical',
        element: 'fire',
        power: 110,
        accuracy: 95,
        mpCost: 15,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 3,
        animation: 'projectile'
      },
      {
        id: 'phase_shift',
        name: '위상 변환',
        description: '일시적으로 물리 공격 면역',
        type: 'buff',
        mpCost: 25,
        cooldown: 8,
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0,
        statusEffect: {
          id: 'ethereal',
          name: '무형',
          type: 'buff',
          stats: { evasion: 0.5 },
          duration: 2,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ],
    weaknesses: ['light'],
    resistances: ['neutral', 'dark']
  },

  lizard_rock: {
    id: 'lizard_rock',
    name: '바위 도마뱀',
    description: '단단한 피부를 가진 도마뱀',
    emoji: '🦎',
    tier: 'common',
    stats: {
      level: 8,
      hp: 95,
      maxHp: 95,
      mp: 35,
      maxMp: 35,
      attack: 16,
      magicAttack: 10,
      defense: 12,
      magicDefense: 8,
      speed: 8,
      accuracy: 95,
      evasion: 0.05,
      critical: 0.1,
      criticalDamage: 1.5,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'rock_throw',
        name: '돌 던지기',
        description: '바위를 던진다',
        type: 'damage',
        damageType: 'physical',
        element: 'earth',
        power: 150,
        accuracy: 85,
        mpCost: 10,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 3,
        animation: 'projectile'
      },
      {
        id: 'harden',
        name: '경화',
        description: '피부를 단단하게 만든다',
        type: 'buff',
        mpCost: 20,
        cooldown: 5,
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0,
        statusEffect: {
          id: 'rock_skin',
          name: '바위 피부',
          type: 'buff',
          stats: { defense: 20, magicDefense: 10 },
          duration: 4,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ],
    weaknesses: ['water', 'ice'],
    resistances: ['fire', 'earth']
  },

  eagle_young: {
    id: 'eagle_young',
    name: '어린 독수리',
    description: '하늘을 나는 맹금류',
    emoji: '🦅',
    tier: 'common',
    stats: {
      level: 9,
      hp: 85,
      maxHp: 85,
      mp: 40,
      maxMp: 40,
      attack: 18,
      magicAttack: 12,
      defense: 7,
      magicDefense: 7,
      speed: 20,
      accuracy: 98,
      evasion: 0.15,
      critical: 0.2,
      criticalDamage: 1.8,
      critRate: 0.1,
      dodgeRate: 0.2
    },
    skills: [
      {
        id: 'dive_attack',
        name: '급강하 공격',
        description: '높은 곳에서 급강하',
        type: 'damage',
        damageType: 'physical',
        element: 'wind',
        power: 180,
        accuracy: 90,
        mpCost: 15,
        cooldown: 3,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash'
      },
      {
        id: 'eagle_eye',
        name: '매의 눈',
        description: '명중률과 치명타율 증가',
        type: 'buff',
        mpCost: 20,
        cooldown: 6,
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0,
        statusEffect: {
          id: 'keen_sight',
          name: '예리한 시야',
          type: 'buff',
          stats: { accuracy: 20, critical: 0.15 },
          duration: 5,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ],
    weaknesses: ['electric'],
    resistances: ['earth']
  },

  crab_beach: {
    id: 'crab_beach',
    name: '해변 게',
    description: '단단한 집게를 가진 게',
    emoji: '🦀',
    tier: 'common',
    stats: {
      level: 10,
      hp: 110,
      maxHp: 110,
      mp: 30,
      maxMp: 30,
      attack: 20,
      magicAttack: 8,
      defense: 15,
      magicDefense: 10,
      speed: 7,
      accuracy: 95,
      evasion: 0.03,
      critical: 0.12,
      criticalDamage: 1.6,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'pincer_attack',
        name: '집게 공격',
        description: '강력한 집게로 집는다',
        type: 'damage',
        damageType: 'physical',
        element: 'neutral',
        power: 160,
        accuracy: 95,
        mpCost: 10,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash'
      },
      {
        id: 'bubble_shield',
        name: '거품 방패',
        description: '거품으로 방어막 생성',
        type: 'buff',
        mpCost: 25,
        cooldown: 5,
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0,
        statusEffect: {
          id: 'bubble_armor',
          name: '거품 갑옷',
          type: 'buff',
          stats: { defense: 25, magicDefense: 15 },
          duration: 3,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ],
    weaknesses: ['electric'],
    resistances: ['water', 'ice']
  },

  // === 중급 몬스터 추가 (레벨 11-20) ===
  wolf_alpha: {
    id: 'wolf_alpha',
    name: '알파 늑대',
    description: '무리의 우두머리 늑대',
    emoji: '🐺',
    tier: 'elite',
    stats: {
      level: 12,
      hp: 180,
      maxHp: 180,
      mp: 60,
      maxMp: 60,
      attack: 35,
      magicAttack: 20,
      defense: 18,
      magicDefense: 15,
      speed: 18,
      accuracy: 95,
      evasion: 0.1,
      critical: 0.18,
      criticalDamage: 1.8,
      critRate: 0.1,
      dodgeRate: 0.2
    },
    skills: [
      {
        id: 'alpha_bite',
        name: '알파의 물기',
        description: '압도적인 힘으로 문다',
        type: 'damage',
        damageType: 'physical',
        element: 'neutral',
        power: 220,
        accuracy: 95,
        mpCost: 20,
        cooldown: 3,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash'
      },
      {
        id: 'pack_howl',
        name: '무리의 울음',
        description: '공격력과 속도 증가',
        type: 'buff',
        mpCost: 30,
        cooldown: 6,
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0,
        statusEffect: {
          id: 'pack_leader',
          name: '무리의 리더',
          type: 'buff',
          stats: { attack: 40, speed: 15 },
          duration: 5,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ]
  },

  bear_brown: {
    id: 'bear_brown',
    name: '갈색 곰',
    description: '거대하고 강력한 곰',
    emoji: '🐻',
    tier: 'common',
    stats: {
      level: 13,
      hp: 200,
      maxHp: 200,
      mp: 40,
      maxMp: 40,
      attack: 32,
      magicAttack: 15,
      defense: 22,
      magicDefense: 18,
      speed: 10,
      accuracy: 95,
      evasion: 0.05,
      critical: 0.15,
      criticalDamage: 2.0,
      critRate: 0.15,
      dodgeRate: 0.25
    },
    skills: [
      {
        id: 'bear_swipe',
        name: '곰 할퀴기',
        description: '거대한 발톱으로 할퀸다',
        type: 'damage',
        damageType: 'physical',
        element: 'neutral',
        power: 200,
        accuracy: 90,
        mpCost: 15,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash'
      },
      {
        id: 'bear_rage',
        name: '곰의 분노',
        description: '분노하여 공격력 증가',
        type: 'buff',
        mpCost: 25,
        cooldown: 5,
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0,
        statusEffect: {
          id: 'enraged',
          name: '격분',
          type: 'buff',
          stats: { attack: 50, criticalDamage: 0.5 },
          duration: 4,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ]
  },

  elemental_fire: {
    id: 'elemental_fire',
    name: '화염 정령',
    description: '불타는 정령',
    emoji: '🔥',
    tier: 'common',
    stats: {
      level: 14,
      hp: 150,
      maxHp: 150,
      mp: 80,
      maxMp: 80,
      attack: 20,
      magicAttack: 40,
      defense: 12,
      magicDefense: 20,
      speed: 15,
      accuracy: 95,
      evasion: 0.08,
      critical: 0.12,
      criticalDamage: 1.6,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'flame_burst',
        name: '화염 폭발',
        description: '강력한 화염 폭발',
        type: 'damage',
        damageType: 'magical',
        element: 'fire',
        power: 180,
        accuracy: 95,
        mpCost: 25,
        cooldown: 3,
        currentCooldown: 0,
        targetType: 'single',
        range: 3,
        animation: 'projectile'
      },
      {
        id: 'burning_aura',
        name: '불타는 오라',
        description: '화염 데미지를 입힌다',
        type: 'buff',
        mpCost: 30,
        cooldown: 6,
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0,
        statusEffect: {
          id: 'fire_shield',
          name: '화염 방패',
          type: 'buff',
          damagePerTurn: 15,
          duration: 5,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ],
    weaknesses: ['water'],
    resistances: ['fire']
  },

  elemental_water: {
    id: 'elemental_water',
    name: '물 정령',
    description: '흐르는 물의 정령',
    emoji: '💧',
    tier: 'common',
    stats: {
      level: 15,
      hp: 160,
      maxHp: 160,
      mp: 90,
      maxMp: 90,
      attack: 18,
      magicAttack: 38,
      defense: 15,
      magicDefense: 22,
      speed: 14,
      accuracy: 95,
      evasion: 0.1,
      critical: 0.1,
      criticalDamage: 1.5,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'water_jet',
        name: '물대포',
        description: '강력한 물줄기 발사',
        type: 'damage',
        damageType: 'magical',
        element: 'water',
        power: 170,
        accuracy: 98,
        mpCost: 20,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 4,
        animation: 'projectile'
      },
      {
        id: 'healing_spring',
        name: '치유의 샘',
        description: 'HP를 회복한다',
        type: 'heal',
        healAmount: 80,
        mpCost: 35,
        cooldown: 5,
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0
      }
    ],
    weaknesses: ['electric'],
    resistances: ['water', 'fire']
  },

  golem_stone: {
    id: 'golem_stone',
    name: '돌 골렘',
    description: '바위로 만들어진 거대한 골렘',
    emoji: '🗿',
    tier: 'common',
    stats: {
      level: 16,
      hp: 250,
      maxHp: 250,
      mp: 50,
      maxMp: 50,
      attack: 38,
      magicAttack: 20,
      defense: 30,
      magicDefense: 25,
      speed: 6,
      accuracy: 95,
      evasion: 0.02,
      critical: 0.08,
      criticalDamage: 1.5,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'stone_fist',
        name: '돌 주먹',
        description: '거대한 돌 주먹으로 내려친다',
        type: 'damage',
        damageType: 'physical',
        element: 'earth',
        power: 220,
        accuracy: 85,
        mpCost: 20,
        cooldown: 3,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash'
      },
      {
        id: 'earthquake',
        name: '지진',
        description: '땅을 흔들어 공격',
        type: 'damage',
        damageType: 'physical',
        element: 'earth',
        power: 150,
        accuracy: 100,
        mpCost: 40,
        cooldown: 5,
        currentCooldown: 0,
        targetType: 'all',
        range: 5,
        animation: 'area'
      }
    ],
    weaknesses: ['water', 'ice'],
    resistances: ['fire', 'poison', 'electric']
  },

  vampire_bat: {
    id: 'vampire_bat',
    name: '흡혈 박쥐',
    description: '피를 빨아먹는 박쥐',
    emoji: '🦇',
    tier: 'common',
    stats: {
      level: 17,
      hp: 140,
      maxHp: 140,
      mp: 60,
      maxMp: 60,
      attack: 28,
      magicAttack: 32,
      defense: 10,
      magicDefense: 18,
      speed: 22,
      accuracy: 95,
      evasion: 0.25,
      critical: 0.15,
      criticalDamage: 1.7,
      critRate: 0.08,
      dodgeRate: 0.18
    },
    skills: [
      {
        id: 'blood_drain',
        name: '흡혈',
        description: '적의 피를 빨아 회복',
        type: 'damage',
        damageType: 'physical',
        element: 'dark',
        power: 120,
        accuracy: 95,
        mpCost: 20,
        cooldown: 3,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash',
        healAmount: 60
      },
      {
        id: 'supersonic',
        name: '초음파',
        description: '혼란을 일으키는 초음파',
        type: 'debuff',
        mpCost: 25,
        cooldown: 5,
        currentCooldown: 0,
        targetType: 'single',
        range: 3,
        animation: 'projectile',
        accuracy: 85,
        power: 0,
        statusEffect: {
          id: 'confused',
          name: '혼란',
          type: 'debuff',
          stats: { accuracy: -50 },
          duration: 3,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ],
    weaknesses: ['light', 'fire'],
    resistances: ['dark']
  },

  minotaur: {
    id: 'minotaur',
    name: '미노타우로스',
    description: '소머리를 가진 거대한 괴물',
    emoji: '🐃',
    tier: 'elite',
    stats: {
      level: 18,
      hp: 280,
      maxHp: 280,
      mp: 70,
      maxMp: 70,
      attack: 45,
      magicAttack: 25,
      defense: 25,
      magicDefense: 20,
      speed: 12,
      accuracy: 95,
      evasion: 0.05,
      critical: 0.2,
      criticalDamage: 2.0,
      critRate: 0.15,
      dodgeRate: 0.25
    },
    skills: [
      {
        id: 'bull_charge',
        name: '황소 돌진',
        description: '강력한 돌진 공격',
        type: 'damage',
        damageType: 'physical',
        element: 'neutral',
        power: 250,
        accuracy: 85,
        mpCost: 25,
        cooldown: 3,
        currentCooldown: 0,
        targetType: 'single',
        range: 2,
        animation: 'projectile'
      },
      {
        id: 'labyrinth_rage',
        name: '미궁의 분노',
        description: '모든 능력치 상승',
        type: 'buff',
        mpCost: 40,
        cooldown: 8,
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0,
        statusEffect: {
          id: 'berserk',
          name: '광폭화',
          type: 'buff',
          stats: { 
            attack: 60, 
            defense: -20, 
            speed: 20,
            criticalDamage: 0.5,
            critRate: 0.01,
            dodgeRate: 0.05
          },
          duration: 5,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ]
  },

  centaur_archer: {
    id: 'centaur_archer',
    name: '켄타우로스 궁수',
    description: '활을 든 반인반마',
    emoji: '🏹',
    tier: 'common',
    stats: {
      level: 19,
      hp: 180,
      maxHp: 180,
      mp: 80,
      maxMp: 80,
      attack: 40,
      magicAttack: 30,
      defense: 18,
      magicDefense: 18,
      speed: 20,
      accuracy: 98,
      evasion: 0.12,
      critical: 0.25,
      criticalDamage: 1.8,
      critRate: 0.1,
      dodgeRate: 0.2
    },
    skills: [
      {
        id: 'precise_shot',
        name: '정밀 사격',
        description: '정확한 화살 공격',
        type: 'damage',
        damageType: 'physical',
        element: 'neutral',
        power: 180,
        accuracy: 100,
        mpCost: 20,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 5,
        animation: 'area'
      },
      {
        id: 'arrow_rain',
        name: '화살비',
        description: '하늘에서 화살이 쏟아진다',
        type: 'damage',
        damageType: 'physical',
        element: 'neutral',
        power: 100,
        accuracy: 85,
        mpCost: 40,
        cooldown: 5,
        currentCooldown: 0,
        targetType: 'all',
        range: 5,
        animation: 'area',
        hitCount: 3
      }
    ]
  },

  mermaid: {
    id: 'mermaid',
    name: '인어',
    description: '아름다운 목소리의 인어',
    emoji: '🧜',
    tier: 'common',
    stats: {
      level: 20,
      hp: 170,
      maxHp: 170,
      mp: 100,
      maxMp: 100,
      attack: 25,
      magicAttack: 45,
      defense: 15,
      magicDefense: 25,
      speed: 16,
      accuracy: 95,
      evasion: 0.15,
      critical: 0.12,
      criticalDamage: 1.6,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'siren_song',
        name: '세이렌의 노래',
        description: '매혹적인 노래로 공격',
        type: 'damage',
        damageType: 'magical',
        element: 'water',
        power: 160,
        accuracy: 95,
        mpCost: 30,
        cooldown: 3,
        currentCooldown: 0,
        targetType: 'single',
        range: 4,
        animation: 'projectile',
        statusEffect: {
          id: 'charmed',
          name: '매혹',
          type: 'debuff',
          stats: { speed: -20, accuracy: -30 },
          duration: 2,
          stackable: false,
          value: 20,
          chance: 100
        }
      },
      {
        id: 'tidal_wave',
        name: '해일',
        description: '거대한 파도로 공격',
        type: 'damage',
        damageType: 'magical',
        element: 'water',
        power: 200,
        accuracy: 90,
        mpCost: 50,
        cooldown: 5,
        currentCooldown: 0,
        targetType: 'all',
        range: 5,
        animation: 'area'
      }
    ],
    weaknesses: ['electric'],
    resistances: ['water', 'ice']
  },

  // === 고급 몬스터 추가 (레벨 21-30) ===
  wyvern_green: {
    id: 'wyvern_green',
    name: '그린 와이번',
    description: '날개 달린 용족',
    emoji: '🐲',
    tier: 'elite',
    stats: {
      level: 22,
      hp: 350,
      maxHp: 350,
      mp: 120,
      maxMp: 120,
      attack: 55,
      magicAttack: 60,
      defense: 30,
      magicDefense: 35,
      speed: 25,
      accuracy: 95,
      evasion: 0.15,
      critical: 0.2,
      criticalDamage: 1.8,
      critRate: 0.1,
      dodgeRate: 0.2
    },
    skills: [
      {
        id: 'poison_breath',
        name: '독 브레스',
        description: '맹독의 숨결',
        type: 'damage',
        damageType: 'magical',
        element: 'poison',
        power: 220,
        accuracy: 90,
        mpCost: 40,
        cooldown: 4,
        currentCooldown: 0,
        targetType: 'all',
        range: 4,
        animation: 'projectile',
        statusEffect: {
          id: 'deadly_poison',
          name: '맹독',
          type: 'debuff',
          damagePerTurn: 25,
          duration: 5,
          stackable: true,
          value: 5,
          chance: 50
        }
      },
      {
        id: 'aerial_ace',
        name: '공중 강습',
        description: '하늘에서 급강하',
        type: 'damage',
        damageType: 'physical',
        element: 'wind',
        power: 280,
        accuracy: 100,
        mpCost: 35,
        cooldown: 3,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash'
      }
    ],
    weaknesses: ['ice'],
    resistances: ['earth', 'poison']
  },

  chimera: {
    id: 'chimera',
    name: '키메라',
    description: '세 개의 머리를 가진 괴물',
    emoji: '🦁',
    tier: 'boss',
    stats: {
      level: 25,
      hp: 500,
      maxHp: 500,
      mp: 150,
      maxMp: 150,
      attack: 70,
      magicAttack: 70,
      defense: 40,
      magicDefense: 40,
      speed: 20,
      accuracy: 95,
      evasion: 0.1,
      critical: 0.18,
      criticalDamage: 2.0,
      critRate: 0.15,
      dodgeRate: 0.25
    },
    skills: [
      {
        id: 'triple_attack',
        name: '삼중 공격',
        description: '세 머리가 동시에 공격',
        type: 'damage',
        damageType: 'physical',
        element: 'neutral',
        power: 120,
        accuracy: 95,
        mpCost: 40,
        cooldown: 3,
        currentCooldown: 0,
        targetType: 'single',
        range: 1,
        animation: 'slash',
        hitCount: 3
      },
      {
        id: 'elemental_breath',
        name: '원소 브레스',
        description: '세 가지 속성의 브레스',
        type: 'damage',
        damageType: 'magical',
        element: 'fire', // 실제로는 fire, poison, electric 혼합
        power: 250,
        accuracy: 85,
        mpCost: 60,
        cooldown: 5,
        currentCooldown: 0,
        targetType: 'all',
        range: 5,
        animation: 'area'
      },
      {
        id: 'regeneration',
        name: '재생',
        description: '상처를 재생한다',
        type: 'heal',
        healAmount: 150,
        mpCost: 50,
        cooldown: 6,
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0
      }
    ]
  },

  phoenix: {
    id: 'phoenix',
    name: '불사조',
    description: '불타는 전설의 새',
    emoji: '🔥',
    tier: 'legendary',
    stats: {
      level: 30,
      hp: 600,
      maxHp: 600,
      mp: 200,
      maxMp: 200,
      attack: 80,
      magicAttack: 100,
      defense: 50,
      magicDefense: 60,
      speed: 30,
      accuracy: 95,
      evasion: 0.2,
      critical: 0.25,
      criticalDamage: 2.0,
      critRate: 0.15,
      dodgeRate: 0.25
    },
    skills: [
      {
        id: 'phoenix_fire',
        name: '불사조의 화염',
        description: '영원히 타오르는 불꽃',
        type: 'damage',
        damageType: 'magical',
        element: 'fire',
        power: 300,
        accuracy: 95,
        mpCost: 50,
        cooldown: 3,
        currentCooldown: 0,
        targetType: 'all',
        range: 6,
        animation: 'area'
      },
      {
        id: 'rebirth',
        name: '환생',
        description: '죽음에서 되살아난다',
        type: 'special',
        mpCost: 100,
        cooldown: 999, // 전투당 1회만
        currentCooldown: 0,
        targetType: 'self',
        range: 0,
        animation: 'buff',
        accuracy: 100,
        power: 0,
        healAmount: 9999 // 완전 회복
      },
      {
        id: 'burning_wings',
        name: '불타는 날개',
        description: '날개의 불꽃으로 공격',
        type: 'damage',
        damageType: 'magical',
        element: 'fire',
        power: 200,
        accuracy: 100,
        mpCost: 40,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 3,
        animation: 'projectile',
        statusEffect: {
          id: 'burn',
          name: '화상',
          type: 'debuff',
          damagePerTurn: 30,
          duration: 5,
          stackable: true,
          value: 5,
          chance: 50
        }
      }
    ],
    weaknesses: ['water'],
    resistances: ['fire', 'light']
  },

  // 더 많은 몬스터들...
  // 여기서는 샘플로 일부만 표시하고 실제로는 100종까지 확장

  demon_imp: {
    id: 'demon_imp',
    name: '임프',
    description: '작은 악마',
    emoji: '😈',
    tier: 'common',
    stats: {
      level: 11,
      hp: 120,
      maxHp: 120,
      mp: 60,
      maxMp: 60,
      attack: 22,
      magicAttack: 28,
      defense: 12,
      magicDefense: 15,
      speed: 18,
      accuracy: 95,
      evasion: 0.15,
      critical: 0.12,
      criticalDamage: 1.6,
      critRate: 0.05,
      dodgeRate: 0.15
    },
    skills: [
      {
        id: 'imp_fireball',
        name: '임프 파이어볼',
        description: '작은 화염구',
        type: 'damage',
        damageType: 'magical',
        element: 'fire',
        power: 140,
        accuracy: 95,
        mpCost: 15,
        cooldown: 2,
        currentCooldown: 0,
        targetType: 'single',
        range: 3,
        animation: 'projectile'
      },
      {
        id: 'mischief',
        name: '장난',
        description: '적을 방해한다',
        type: 'debuff',
        mpCost: 20,
        cooldown: 4,
        currentCooldown: 0,
        targetType: 'single',
        range: 3,
        animation: 'projectile',
        accuracy: 90,
        power: 0,
        statusEffect: {
          id: 'distracted',
          name: '산만함',
          type: 'debuff',
          stats: { accuracy: -25, evasion: -0.1 },
          duration: 3,
          stackable: false,
          value: 20,
          chance: 100
        }
      }
    ],
    weaknesses: ['light'],
    resistances: ['fire', 'dark']
  }
}