name: 테스트 자동 실행

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 가져오기
      uses: actions/checkout@v3

    - name: Node.js 설정
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: 의존성 설치
      run: npm ci

    - name: 단위 테스트 실행
      run: npm test -- --coverage --watchAll=false

    - name: Playwright 설치
      run: npx playwright install --with-deps

    - name: E2E 테스트 실행
      run: npx playwright test

    - name: 테스트 결과 업로드
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: 커버리지 리포트
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: false